server:
  ## true für HTTPS, false für HTTP
  useHTTPS: true 
  
  ## port number
  port: 8443 

  ## path to SSL/TLS cert file and private key file
  certFile: /certs/tls.crt  
  keyFile: /certs/tls.key 

  ## path to client CA certificate
  clientCAFile: /certs/ca.crt
prometheus:
  url: "http://prometheus-operated.monitoring.svc.cluster.local:9090"
  resource: "/api/v1/query"
  query:
    memory:
      usage: 'sum(quantile_over_time(0.9, container_memory_usage_bytes{}[7d]))'
      request: 'namespace_memory:kube_pod_container_resource_requests:sum{}'
    cpu:
      usage: 'sum(quantile_over_time(0.9,rate(container_cpu_usage_seconds_total{}[1m])[7d:5m]))'
      request: 'namespace_cpu:kube_pod_container_resource_requests:sum{}'
