apiVersion: v1
kind: Namespace
metadata:
  name: prometheus-provider
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-provider
  namespace: prometheus-provider
spec:
  replicas: 1
  selector:
    matchLabels:
      run: prometheus-provider
  template:
    metadata:
      labels:
        run: prometheus-provider
    spec:
      containers:
      - image: danzim/prometheus-provider:latest
        imagePullPolicy: IfNotPresent
        name: prometheus-provider
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          requests:
            memory: 64Mi
            cpu: 50m
          limits:
            memory: 128Mi
            cpu: 200m
      restartPolicy: Always
      nodeSelector:
        kubernetes.io/os: linux