apiVersion: v1
kind: Service
metadata:
  name: prometheus-provider
  namespace: prometheus-provider
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: prometheus-provider
  sessionAffinity: None
